apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: keyrock
  name: keyrock
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: keyrock
  type: LoadBalancer
status:
  loadBalancer: {}
